### PR TITLE
Remove S2S Types

### PR DESCRIPTION
**Pull request by acgxv**
Revert #4.

Because these are built-in types, they are alive in Polkadot JS now.

@sxlwar  Could you test these changes with Polkadot Apps?

From my testing, all works well.

A local test URL http://localhost:3000/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network#/explorer/query/488548 might be helpful.

### CODE REVIEW

**Comment by sxlwar** [comment]
image

can get the 488458 block correctly

**Comment by acgxv** [comment]
What about the others issue that you encounter?

**Comment by sxlwar** [comment]
I will test these changes in subql later to confirm that works or not

**Comment by sxlwar** [comment]
works fine  in subql

**Comment by sxlwar** [comment]
clean some types that implemented in Polkadot
@AurevoirXavier @WoeOm help to review  pls

**Comment by acgxv** [comment]
Great job. LGTM.

**Pull request merged**
