### PR TITLE
Adapt darwinia v0.11.1 types

### PR DESCRIPTION
**Pull request by WoeOm**
npm published : @darwinia/types-known@1.1.0-alpha.22

### CODE REVIEW

**Review by hackfisher — CHANGES_REQUESTED** [review]
If this is for 0.11.0, need to wait and merge after 0.10.1.

Campanion pr for 0.10.1 go first.

Pending

**Comment by hackfisher** [comment]
Pangolin is using up to date type, different with Crab and Darwinia

**Review by hackfisher — APPROVED** [review]
Crab and Darwinia 0.10.1 will also use these new added custom types.

**Review by sxlwar — APPROVED** [review]

**Review by sxlwar — APPROVED** [review]

**Comment by WoeOm** [comment]
@darwinia/api-options@1.1.0-alpha.23

**Pull request merged**
